[theme]
base = "light"
primaryColor = "#5360A0"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#15243B"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
